//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineField.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MineField.Common.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done, you have won at position {0}, lives remaining: {1}, moves made: {2}.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current status is: position {0}, lives remaining: {1}, moves made: {2}.
        /// </summary>
        public static string Current_Status {
            get {
                return ResourceManager.GetString("Current Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over, you have run out of lives at position {0}, lives remaining: {1}, moves made: {2}.
        /// </summary>
        public static string EndOfGame {
            get {
                return ResourceManager.GetString("EndOfGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character entered. Only the following are permitted: Up, Down, Left and Right..
        /// </summary>
        public static string InvalidUserInput {
            get {
                return ResourceManager.GetString("InvalidUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already at the bottom of the board. Current position {0}, lives remaining: {1}, moves made: {2}.
        /// </summary>
        public static string OffTheBottomOfTheBoard {
            get {
                return ResourceManager.GetString("OffTheBottomOfTheBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already at the left edge of the board. Current position {0}, lives remaining: {1}, moves made: {2}.
        /// </summary>
        public static string OffTheLeftOfTheBoard {
            get {
                return ResourceManager.GetString("OffTheLeftOfTheBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already at the right edge of the board. Current position {0}, lives remaining: {1}, moves made: {2}.
        /// </summary>
        public static string OffTheRightOfTheBoard {
            get {
                return ResourceManager.GetString("OffTheRightOfTheBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the game.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
